---
- name: Install ufw
  ansible.builtin.apt:
    name:
      - ufw
    state: present
  become: true
- name: Start ufw
  ansible.builtin.systemd:
    name: ufw
    enabled: true
    state: started
  become: true
- name: Add rules
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    from_ip: "{{ item.src }}"
    to_ip: "{{ item.dest }}"
    state: reloaded
  loop: "{{ fw_rules }}"
  become: true
- name: Enable ufw
  community.general.ufw:
    state: enabled
    policy: deny
  become: true
