# SPDX-License-Identifier: MIT
---
- name: (Debian/Ubuntu) Install mariadb
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pip
    state: present
  become: true
  when: ansible_os_family == "Debian"
- name: (AlmaLinux/RHEL) Install mariadb
  ansible.builtin.dnf:
    name:
      - mariadb-server
      - python3-pip
    state: present
  become: true
  when: ansible_os_family == "RedHat"
- name: Start mariadb
  ansible.builtin.systemd:
    name: mariadb
    state: started
    enabled: true
  become: true
- name: Install required packages
  ansible.builtin.pip:
    name:
      - PyMySQL
    state: present
- name: Deploy config file
  ansible.builtin.template:
    src: etc/my.cnf.d/mariadb-server.cnf.j2
    dest: /etc/my.cnf.d/mariadb-server.cnf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart mariadb
