# SPDX-License-Identifier: MIT
---
- name: (Debian/Ubuntu) Install squid
  ansible.builtin.apt:
    name:
      - squid
    state: present
  become: true
  when: ansible_facts["os_family"] == "Debian"
- name: (AlmaLinux/Amazon Linux/RHEL) Install squid
  ansible.builtin.dnf:
    name:
      - squid
    state: present
  become: true
  when: ansible_facts["os_family"] == "RedHat"
- name: Start squid
  ansible.builtin.systemd:
    name: squid
    state: started
    enabled: true
  become: true
