---
- name: Install Kubernetes
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster
  vars:
    kube_version: v1.30.4
    kube_network_plugin: flannel
    kubeconfig_localhost: true
    kubectl_localhost: true
    helm_enabled: true
    metrics_server_enabled: true
    cert_manager_enabled: true
