---
name: Lint
on:
  push:

permissions:
  contents: read

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: ansible lint
        run: ansible-lint roles playbooks
